// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NRZMyk.Services.Data;

#nullable disable

namespace NRZMyk.Services.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220219144356_Initial_MySql")]
    partial class Initial_MySql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NRZMyk.Services.Data.Entities.AntimicrobialSensitivityTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AntifungalAgent")
                        .HasColumnType("int");

                    b.Property<int?>("ClinicalBreakpointId")
                        .HasColumnType("int");

                    b.Property<float>("MinimumInhibitoryConcentration")
                        .HasColumnType("float");

                    b.Property<int>("Resistance")
                        .HasColumnType("int");

                    b.Property<int?>("SentinelEntryId")
                        .HasColumnType("int");

                    b.Property<int>("TestingMethod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicalBreakpointId");

                    b.HasIndex("SentinelEntryId");

                    b.ToTable("AntimicrobialSensitivityTest");
                });

            modelBuilder.Entity("NRZMyk.Services.Data.Entities.ClinicalBreakpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AntifungalAgent")
                        .HasColumnType("int");

                    b.Property<string>("AntifungalAgentDetails")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<float?>("MicBreakpointResistent")
                        .HasColumnType("float");

                    b.Property<float?>("MicBreakpointSusceptible")
                        .HasColumnType("float");

                    b.Property<int>("Species")
                        .HasColumnType("int");

                    b.Property<int>("Standard")
                        .HasColumnType("int");

                    b.Property<float?>("TechnicalUncertainty")
                        .HasColumnType("float");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Standard", "Version", "Species", "AntifungalAgentDetails")
                        .IsUnique();

                    b.ToTable("ClinicalBreakpoints");
                });

            modelBuilder.Entity("NRZMyk.Services.Data.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("NRZMyk.Services.Data.Entities.RemoteAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Postalcode")
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("RemoteAccounts");
                });

            modelBuilder.Entity("NRZMyk.Services.Data.Entities.SentinelEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgeGroup")
                        .HasColumnType("int");

                    b.Property<int>("CryoBoxNumber")
                        .HasColumnType("int");

                    b.Property<int>("CryoBoxSlot")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CryoDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CryoRemark")
                        .HasColumnType("longtext");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("HospitalDepartment")
                        .HasColumnType("int");

                    b.Property<int>("HospitalDepartmentType")
                        .HasColumnType("int");

                    b.Property<int>("IdentifiedSpecies")
                        .HasColumnType("int");

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<string>("OtherHospitalDepartment")
                        .HasColumnType("longtext");

                    b.Property<string>("OtherIdentifiedSpecies")
                        .HasColumnType("longtext");

                    b.Property<string>("OtherMaterial")
                        .HasColumnType("longtext");

                    b.Property<string>("PcrDetails")
                        .HasColumnType("longtext");

                    b.Property<string>("ProtectKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SamplingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SenderLaboratoryNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("SpeciesIdentificationMethod")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("YearlySequentialEntryNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProtectKey");

                    b.HasIndex("CryoBoxNumber", "CryoBoxSlot")
                        .IsUnique();

                    b.HasIndex("Year", "YearlySequentialEntryNumber")
                        .IsUnique();

                    b.ToTable("SentinelEntries");
                });

            modelBuilder.Entity("NRZMyk.Services.Data.Entities.AntimicrobialSensitivityTest", b =>
                {
                    b.HasOne("NRZMyk.Services.Data.Entities.ClinicalBreakpoint", "ClinicalBreakpoint")
                        .WithMany("AntimicrobialSensitivityTests")
                        .HasForeignKey("ClinicalBreakpointId");

                    b.HasOne("NRZMyk.Services.Data.Entities.SentinelEntry", "SentinelEntry")
                        .WithMany("AntimicrobialSensitivityTests")
                        .HasForeignKey("SentinelEntryId");

                    b.Navigation("ClinicalBreakpoint");

                    b.Navigation("SentinelEntry");
                });

            modelBuilder.Entity("NRZMyk.Services.Data.Entities.RemoteAccount", b =>
                {
                    b.HasOne("NRZMyk.Services.Data.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("NRZMyk.Services.Data.Entities.ClinicalBreakpoint", b =>
                {
                    b.Navigation("AntimicrobialSensitivityTests");
                });

            modelBuilder.Entity("NRZMyk.Services.Data.Entities.Organization", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("NRZMyk.Services.Data.Entities.SentinelEntry", b =>
                {
                    b.Navigation("AntimicrobialSensitivityTests");
                });
#pragma warning restore 612, 618
        }
    }
}
