// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NRZMyk.Services.Data;

namespace NRZMyk.Services.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200804050114_ClinicalBreakpoints_Initial")]
    partial class ClinicalBreakpoints_Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NRZMyk.Services.Data.Entities.ClinicalBreakpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AntifungalAgent")
                        .HasColumnType("int");

                    b.Property<string>("AntifungalAgentDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("MicBreakpointResistent")
                        .HasColumnType("real");

                    b.Property<float?>("MicBreakpointSusceptible")
                        .HasColumnType("real");

                    b.Property<int>("Species")
                        .HasColumnType("int");

                    b.Property<int>("Standard")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Standard", "Version", "AntifungalAgentDetails")
                        .IsUnique();

                    b.ToTable("ClinicalBreakpoints");
                });

            modelBuilder.Entity("NRZMyk.Services.Data.Entities.SentinelEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgeGroup")
                        .HasColumnType("int");

                    b.Property<string>("IdentifiedSpecies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidentialTreatment")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SamplingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenderLaboratoryNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesTestingMethod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SentinelEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
