name: Release
on:
  release:
    types: [published]
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    environment: ci
    permissions:
      contents: read
    steps:
      - name: Login to Azure Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: sivregistrymr.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag and push docker image
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        shell: bash
        run: |
          docker pull sivregistrymr.azurecr.io/nrzmyk:latest
          docker tag sivregistrymr.azurecr.io/nrzmyk:latest sivregistrymr.azurecr.io/nrzmyk:stable
          docker tag sivregistrymr.azurecr.io/nrzmyk:latest "sivregistrymr.azurecr.io/nrzmyk:$RELEASE_TAG"
          docker push sivregistrymr.azurecr.io/nrzmyk:stable
          docker push "sivregistrymr.azurecr.io/nrzmyk:$RELEASE_TAG"
